### ISSUE TITLE
What is dbt?

### ISSUE THREAD

**Issue by SgtPooki** [davidgasquez/datadex#9]
I didn't know what dbt was until I found https://docs.getdbt.com/docs/introduction after reading the README.md in this repo. I think a short description that explains what dbt is, and more about how this tool uses dbt, could be a useful update to the readme.

**Comment by davidgasquez** [comment]
Thanks @SgtPooki! I can see how confusing is this right now. Will add a small section explaining the different tools that Datadex uses.

**Comment by davidgasquez** [comment]
Fixed in https://github.com/davidgasquez/datadex/commit/e63d634a448459a488b149fc8132deeac819dc7f! Thanks again @SgtPooki for the issue.
